apiVersion: v1
kind: Service
metadata:
  name: cribseekers-api-service
  namespace: cribseekers
  labels:
    app: cribseekers-api
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: websocket
  selector:
    app: cribseekers-api
