export const API_ROUTES = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
  },
  USERS: {
    ME: '/users/me',
    PROFILE: '/users/profile',
    UPDATE_PROFILE: '/users/profile',
  },
  PROPERTIES: {
    LIST: '/properties',
    DETAIL: '/properties/:id',
    CREATE: '/properties',
    UPDATE: '/properties/:id',
    DELETE: '/properties/:id',
    MY_PROPERTIES: '/properties/my',
    SEARCH: '/properties/search',
    NEARBY: '/properties/nearby',
  },
  INSPECTIONS: {
    LIST: '/inspections',
    DETAIL: '/inspections/:id',
    CREATE: '/inspections',
    UPDATE: '/inspections/:id',
    DELETE: '/inspections/:id',
    MY_INSPECTIONS: '/inspections/my',
    APPROVE: '/inspections/:id/approve',
    CANCEL: '/inspections/:id/cancel',
  },
  PAYMENTS: {
    LIST: '/payments',
    DETAIL: '/payments/:id',
    INITIALIZE: '/payments/initialize',
    VERIFY: '/payments/verify/:reference',
    REFUND: '/payments/:id/refund',
  },
  WALLET: {
    BALANCE: '/wallet/balance',
    TRANSACTIONS: '/wallet/transactions',
    FUND: '/wallet/fund',
    WITHDRAW: '/wallet/withdraw',
    TRANSFER: '/wallet/transfer',
  },
  AGENTS: {
    LIST: '/agents',
    DETAIL: '/agents/:id',
    VERIFY: '/agents/:id/verify',
    REVIEWS: '/agents/:id/reviews',
  },
  REVIEWS: {
    LIST: '/reviews',
    DETAIL: '/reviews/:id',
    CREATE: '/reviews',
    UPDATE: '/reviews/:id',
    DELETE: '/reviews/:id',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_READ: '/notifications/:id/read',
    MARK_ALL_READ: '/notifications/read-all',
    SETTINGS: '/notifications/settings',
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations',
    MESSAGES: '/chat/conversations/:id/messages',
    SEND: '/chat/conversations/:id/messages',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    PROPERTIES: '/admin/properties',
    INSPECTIONS: '/admin/inspections',
    PAYMENTS: '/admin/payments',
    AGENTS: '/admin/agents',
    SETTINGS: '/admin/settings',
  },
  HEALTH: '/health',
} as const;
