export const API_ENDPOINTS = {
  // Auth
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  LOGOUT: '/auth/logout',
  REFRESH: '/auth/refresh',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFY_EMAIL: '/auth/verify-email',
  VERIFY_PHONE: '/auth/verify-phone',
  VERIFY_OTP: '/auth/verify-otp',
  CHANGE_PASSWORD: '/auth/change-password',

  // Users
  ME: '/users/me',
  UPDATE_PROFILE: '/users/me',
  CHANGE_PASSWORD_USER: '/users/me/password',
  UPLOAD_AVATAR: '/users/me/avatar',
  KYC_SUBMIT: '/users/me/kyc',
  KYC_STATUS: '/users/me/kyc/status',
  USER_BY_ID: (id: string) => `/users/${id}`,

  // Properties
  PROPERTIES: '/properties',
  PROPERTY_CREATE: '/properties',
  PROPERTY_SEARCH: '/properties/search',
  PROPERTY_FEATURED: '/properties/featured',
  PROPERTY_PUBLISHED: '/properties/published',
  PROPERTY_DRAFTS: '/properties/drafts',
  PROPERTY_PENDING: '/properties/pending',
  PROPERTY_REJECTED: '/properties/rejected',
  PROPERTY_BY_ID: (id: string) => `/properties/${id}`,
  PROPERTY_UPDATE: (id: string) => `/properties/${id}`,
  PROPERTY_DELETE: (id: string) => `/properties/${id}`,
  PROPERTY_SUMMARY: (id: string) => `/properties/${id}/summary`,
  PROPERTY_PUBLISH: (id: string) => `/properties/${id}/publish`,
  PROPERTY_UNPUBLISH: (id: string) => `/properties/${id}/unpublish`,
  PROPERTY_VERIFY: (id: string) => `/properties/${id}/verify`,
  PROPERTY_ARCHIVE: (id: string) => `/properties/${id}/archive`,
  PROPERTY_DUPLICATE: (id: string) => `/properties/${id}/duplicate`,
  PROPERTY_FEATURE: (id: string) => `/properties/${id}/feature`,
  PROPERTY_UNFEATURE: (id: string) => `/properties/${id}/unfeature`,
  PROPERTY_INCREMENT_VIEWS: (id: string) => `/properties/${id}/views`,
  PROPERTY_INCREMENT_INQUIRIES: (id: string) => `/properties/${id}/inquiries`,
  PROPERTY_ANALYTICS: (id: string) => `/properties/${id}/analytics`,
  PROPERTY_IMAGES: (id: string) => `/properties/${id}/images`,
  PROPERTY_AMENITIES: (id: string) => `/properties/${id}/amenities`,
  PROPERTY_NEARBY: (id: string) => `/properties/${id}/nearby`,
  PROPERTY_TIMELINE: (id: string) => `/properties/${id}/timeline`,
  PROPERTY_DOCUMENTS: (id: string) => `/properties/${id}/documents`,
  PROPERTY_REVIEWS: (id: string) => `/properties/${id}/reviews`,
  PROPERTY_AVAILABILITY: (id: string) => `/properties/${id}/availability`,
  PROPERTY_SETTINGS: (id: string) => `/properties/${id}/settings`,

  // Search
  SEARCH_GLOBAL: '/search',
  SEARCH_KEYWORD: '/search/keyword',
  SEARCH_STATE: (state: string) => `/search/state/${state}`,
  SEARCH_CITY: (city: string) => `/search/city/${city}`,
  SEARCH_LGA: (lga: string) => `/search/lga/${lga}`,
  SEARCH_ESTATE: (estate: string) => `/search/estate/${estate}`,
  SEARCH_CATEGORY: (categoryId: string) => `/search/category/${categoryId}`,
  SEARCH_TYPE: (typeId: string) => `/search/type/${typeId}`,
  SEARCH_PURPOSE: (purposeId: string) => `/search/purpose/${purposeId}`,
  SEARCH_FEATURED: '/search/featured',
  SEARCH_RECENT: '/search/recent',
  SEARCH_POPULAR: '/search/popular',
  SEARCH_SUGGESTIONS: '/search/suggestions',

  // Inspections
  INSPECTIONS: '/inspections',
  INSPECTION_BY_ID: (id: string) => `/inspections/${id}`,
  INSPECTION_BY_PROPERTY: (propertyId: string) => `/inspections/property/${propertyId}`,
  INSPECTION_BY_USER: (userId: string) => `/inspections/user/${userId}`,
  INSPECTION_CONFIRM: (id: string) => `/inspections/${id}/confirm`,
  INSPECTION_CANCEL: (id: string) => `/inspections/${id}/cancel`,
  INSPECTION_RESCHEDULE: (id: string) => `/inspections/${id}/reschedule`,
  INSPECTION_PARTICIPANTS: (id: string) => `/inspections/${id}/participants`,

  // Wallet
  WALLET_CREATE: (userId: string) => `/wallets/users/${userId}`,
  WALLET_BY_ID: (id: string) => `/wallets/${id}`,
  WALLET_BY_USER: (userId: string) => `/wallets/user/${userId}`,
  WALLET_TRANSACTIONS: (id: string) => `/wallets/${id}/transactions`,
  WALLET_SUMMARY: (id: string) => `/wallets/${id}/summary`,
  WALLET_FREEZE: (id: string) => `/wallets/${id}/freeze`,
  WALLET_UNFREEZE: (id: string) => `/wallets/${id}/unfreeze`,
  WALLET_CLOSE: (id: string) => `/wallets/${id}/close`,

  // Escrow
  ESCROWS: '/escrows',
  ESCROW_CREATE: '/escrows',
  ESCROW_BY_ID: (id: string) => `/escrows/${id}`,
  ESCROW_BY_PAYER: (payerId: string) => `/escrows/payer/${payerId}`,
  ESCROW_BY_PAYEE: (payeeId: string) => `/escrows/payee/${payeeId}`,
  ESCROW_RELEASE: (id: string) => `/escrows/${id}/release`,
  ESCROW_REFUND: (id: string) => `/escrows/${id}/refund`,
  ESCROW_DISPUTE: (id: string) => `/escrows/${id}/dispute`,

  // Communication
  CONVERSATIONS: '/communication/conversations',
  CONVERSATION_SEARCH: '/communication/conversations/search',
  CONVERSATION_BY_ID: (id: string) => `/communication/conversations/${id}`,
  CONVERSATION_SUMMARY: (id: string) => `/communication/conversations/${id}/summary`,
  CONVERSATION_ARCHIVE: (id: string) => `/communication/conversations/${id}/archive`,
  CONVERSATION_UNARCHIVE: (id: string) => `/communication/conversations/${id}/unarchive`,

  // Notifications
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_BY_ID: (id: string) => `/notifications/${id}`,
  NOTIFICATION_MARK_READ: (id: string) => `/notifications/${id}/read`,
  NOTIFICATION_MARK_DISMISS: (id: string) => `/notifications/${id}/dismiss`,
  NOTIFICATION_BY_USER: (userId: string) => `/notifications/user/${userId}`,
  NOTIFICATION_UNREAD: (userId: string) => `/notifications/user/${userId}/unread`,

  // Storage / Media
  STORAGE_UPLOAD: '/storage/upload',
  STORAGE_UPLOAD_BULK: '/storage/upload/bulk',
  STORAGE_LIST: '/storage',
  STORAGE_FILE: (id: string) => `/storage/${id}`,
  STORAGE_SIGNED_URL: (id: string) => `/storage/${id}/signed-url`,
  STORAGE_UPDATE: (id: string) => `/storage/${id}`,
  STORAGE_REPLACE: (id: string) => `/storage/${id}/replace`,
  STORAGE_MOVE: (id: string) => `/storage/${id}/move`,
  STORAGE_COPY: (id: string) => `/storage/${id}/copy`,
  STORAGE_RESTORE: (id: string) => `/storage/${id}/restore`,
  STORAGE_DELETE: (id: string) => `/storage/${id}`,

  // Admin
  ADMIN_USERS_MODERATE: '/admin/users/moderate',
  ADMIN_USERS_SUSPEND: '/admin/users/suspend',
  ADMIN_USERS_REACTIVATE: '/admin/users/reactivate',
  ADMIN_USERS_DELETE: '/admin/users/delete',
  ADMIN_PROPERTIES_APPROVE: '/admin/properties/approve',
  ADMIN_PROPERTIES_REJECT: '/admin/properties/reject',
  ADMIN_WALLETS_FREEZE: '/admin/wallets/freeze',
  ADMIN_WALLETS_UNFREEZE: '/admin/wallets/unfreeze',
  ADMIN_WITHDRAWALS_APPROVE: '/admin/withdrawals/approve',
  ADMIN_WITHDRAWALS_REJECT: '/admin/withdrawals/reject',
  ADMIN_ACTIONS: (adminId: string) => `/admin/actions/${adminId}`,
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_ACTIVITY_LOGS: '/admin/activity-logs',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_SETTINGS: '/admin/settings',

  // Webhooks (no auth required)
  WEBHOOK_PAYSTACK: '/webhooks/paystack',
  WEBHOOK_FLUTTERWAVE: '/webhooks/flutterwave',
} as const;
