export enum PropertyStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  RENTED = 'RENTED',
  SOLD = 'SOLD',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum InspectionStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  SYSTEM = 'SYSTEM',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  AGENT = 'AGENT',
  LANDLORD = 'LANDLORD',
  TENANT = 'TENANT',
}

export enum Permission {
  // Property permissions
  CREATE_PROPERTY = 'CREATE_PROPERTY',
  READ_PROPERTY = 'READ_PROPERTY',
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  DELETE_PROPERTY = 'DELETE_PROPERTY',
  MANAGE_PROPERTY_STATUS = 'MANAGE_PROPERTY_STATUS',

  // Inspection permissions
  CREATE_INSPECTION = 'CREATE_INSPECTION',
  READ_INSPECTION = 'READ_INSPECTION',
  UPDATE_INSPECTION = 'UPDATE_INSPECTION',
  DELETE_INSPECTION = 'DELETE_INSPECTION',
  APPROVE_INSPECTION = 'APPROVE_INSPECTION',

  // User permissions
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_AGENTS = 'MANAGE_AGENTS',
  VERIFY_AGENT = 'VERIFY_AGENT',

  // Payment permissions
  PROCESS_PAYMENT = 'PROCESS_PAYMENT',
  REFUND_PAYMENT = 'REFUND_PAYMENT',
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',

  // Admin permissions
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',
}

export enum PropertyType {
  APARTMENT = 'APARTMENT',
  HOUSE = 'HOUSE',
  FLAT = 'FLAT',
  STUDIO = 'STUDIO',
  DUPLEX = 'DUPLEX',
  TERRACE = 'TERRACE',
  BUNGALOW = 'BUNGALOW',
  COMMERCIAL = 'COMMERCIAL',
  LAND = 'LAND',
  OFFICE = 'OFFICE',
  WAREHOUSE = 'WAREHOUSE',
}

export enum ListingType {
  RENT = 'RENT',
  SALE = 'SALE',
  SHORT_LET = 'SHORT_LET',
}

export enum FurnishingType {
  FURNISHED = 'FURNISHED',
  SEMI_FURNISHED = 'SEMI_FURNISHED',
  UNFURNISHED = 'UNFURNISHED',
}
