import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BedDouble, Bath, MapPin, Search, SlidersHorizontal, Heart, Star, ShieldCheck, CalendarDays, Sparkles, ChevronDown, Menu, X, KeyRound, WalletCards, MessageCircle, CircleCheck, House } from 'lucide-react';
import './styles.css';

const properties = [
  { id: 1, name: 'The Ivory House', place: 'Ikoyi, Lagos', price: '₦12.5M', period: '/ year', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85', beds: 4, baths: 4, area: '420 sqm', tag: 'Verified', tone: 'olive' },
  { id: 2, name: 'Parkview Residence', place: 'Lekki Phase 1, Lagos', price: '₦8.2M', period: '/ year', image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=85', beds: 3, baths: 3, area: '265 sqm', tag: 'New listing', tone: 'gold' },
  { id: 3, name: 'Solace Apartments', place: 'Maitama, Abuja', price: '₦5.6M', period: '/ year', image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85', beds: 2, baths: 2, area: '180 sqm', tag: 'Verified', tone: 'olive' },
];

function PropertyCard({ property }) {
  const [saved, setSaved] = useState(false);
  return <article className="property-card">
    <div className="property-image"><img src={property.image} alt={property.name} /><span className={`tag ${property.tone}`}>{property.tag === 'Verified' && <ShieldCheck size={13}/>} {property.tag}</span><button className={`heart ${saved ? 'saved' : ''}`} onClick={() => setSaved(!saved)} aria-label="Save property"><Heart size={18} fill={saved ? 'currentColor' : 'none'} /></button></div>
    <div className="property-content"><p className="property-place"><MapPin size={14}/>{property.place}</p><h3>{property.name}</h3><div className="details"><span><BedDouble size={16}/>{property.beds} beds</span><span><Bath size={16}/>{property.baths} baths</span><span>{property.area}</span></div><div className="property-footer"><div><strong>{property.price}</strong><small>{property.period}</small></div><button className="round-arrow" aria-label={`View ${property.name}`}><ArrowRight size={17}/></button></div></div>
  </article>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  return <div className="app-shell">
    <header className="nav"><a className="brand" href="#top" aria-label="CribSeekers home"><span className="brand-mark">c</span><span>crib<span>seekers</span></span></a><nav className={menuOpen ? 'open' : ''}><a href="#discover">Discover</a><a href="#how">How it works</a><a href="#trust">Why CribSeekers</a><a href="#help">Help center</a></nav><div className="nav-actions"><button className="icon-button search-mini" onClick={() => setSearchOpen(!searchOpen)} aria-label="Open search"><Search size={19}/></button><a className="login" href="#login">Log in</a><a className="join" href="#signup">Create account <ArrowRight size={16}/></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</button></div></header>

    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> Nigeria's trusted home search</p><h1>Find a place that <em>feels like you.</em></h1><p className="lede">Discover thoughtfully verified homes, book inspections with confidence, and secure your next move—all in one place.</p><div className="hero-proof"><div className="avatars"><i></i><i></i><i></i><i></i></div><p><strong>10,000+</strong> people found a place to call home</p></div></div><div className="hero-visual"><div className="hero-photo"><img src="https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1500&q=90" alt="Modern luxury home"/></div><div className="float-card inspection"><div className="float-icon"><CalendarDays size={20}/></div><div><small>Next inspection</small><strong>Saturday, 10:00 AM</strong><span>Parkview Residence</span></div></div><div className="float-card verified"><ShieldCheck size={21}/><div><strong>Every home, verified</strong><span>Move with confidence</span></div></div></div></section>

      <section className={`search-panel ${searchOpen ? 'expanded' : ''}`} aria-label="Property search"><div className="search-field"><MapPin size={20}/><div><label>Location</label><button>Where do you want to live?</button></div></div><div className="search-field"><House size={20}/><div><label>Property type</label><button>Any type <ChevronDown size={15}/></button></div></div><div className="search-field"><WalletCards size={20}/><div><label>Budget</label><button>Any price <ChevronDown size={15}/></button></div></div><button className="filter-button" aria-label="More filters"><SlidersHorizontal size={20}/></button><button className="search-button"><Search size={19}/> <span>Search homes</span></button></section>

      <section className="trust-strip" id="trust"><div><ShieldCheck/><span><strong>Verified listings</strong>Every property is reviewed</span></div><div><CalendarDays/><span><strong>Easy inspections</strong>Book in a few taps</span></div><div><KeyRound/><span><strong>Secure transactions</strong>Protected escrow payments</span></div><div><MessageCircle/><span><strong>Direct conversations</strong>Chat with property owners</span></div></section>

      <section className="section feature-section" id="discover"><div className="section-heading"><div><p className="eyebrow">Handpicked for you</p><h2>Homes worth seeing in person.</h2></div><a className="text-link" href="#search">Explore all homes <ArrowRight size={16}/></a></div><div className="property-grid">{properties.map(p => <PropertyCard key={p.id} property={p}/>)}</div></section>

      <section className="ai-banner"><div className="ai-shape one"></div><div className="ai-shape two"></div><div className="ai-content"><p className="eyebrow"><Sparkles size={15}/> Meet your homefinding assistant</p><h2>Tell us what matters.<br/><em>We'll do the searching.</em></h2><p>Our AI learns your preferences, understands your lifestyle, and surfaces homes that genuinely fit.</p><button className="light-button">Try AI Search <ArrowRight size={17}/></button></div><div className="ai-card"><div className="ai-card-top"><span className="ai-orb"><Sparkles size={18}/></span><span>Crib AI</span><i></i></div><p>“I found three quiet, pet-friendly flats within 20 minutes of your office.”</p><div className="ai-result"><img src={properties[2].image} alt="Apartment recommendation"/><div><strong>Solace Apartments</strong><span>Maitama, Abuja · ₦5.6M/year</span></div><CircleCheck size={18}/></div></div></section>

      <section className="section how-section" id="how"><div className="section-heading center"><p className="eyebrow">A better way to move</p><h2>From first search to front door.</h2><p>Everything you need for a confident property decision, beautifully connected.</p></div><div className="steps"><div className="step"><span>01</span><div className="step-icon"><Search/></div><h3>Discover your match</h3><p>Search verified properties or let AI narrow down what feels right.</p></div><div className="step"><span>02</span><div className="step-icon"><CalendarDays/></div><h3>See it for yourself</h3><p>Book, manage, and track inspections without the back-and-forth.</p></div><div className="step"><span>03</span><div className="step-icon"><KeyRound/></div><h3>Secure it safely</h3><p>Pay with clarity and confidence through our protected escrow.</p></div></div></section>

      <section className="city-section"><div className="city-copy"><p className="eyebrow">Made for your next chapter</p><h2>Explore the places<br/>that move Nigeria.</h2><p>From Lagos' lively neighborhoods to Abuja's calm corners, find a home in the city that suits your pace.</p><a href="#locations" className="dark-link">Browse locations <ArrowRight size={17}/></a></div><div className="city-grid"><div className="city city-large"><img src="https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=900&q=80" alt="Lagos city"/><span>Lagos <small>2,400+ homes</small></span></div><div className="city"><img src="https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?auto=format&fit=crop&w=700&q=80" alt="Abuja architecture"/><span>Abuja <small>1,180+ homes</small></span></div></div></section>

      <section className="testimonial"><div className="quote-mark">“</div><blockquote>CribSeekers took the stress out of moving. I found my apartment, inspected it, and handled payment without a single surprise.</blockquote><div className="reviewer"><div className="review-avatar">AO</div><div><strong>Amara Okafor</strong><span>Tenant, Lekki</span></div><div className="stars">{[1,2,3,4,5].map(x=><Star key={x} size={15} fill="currentColor"/> )}</div></div></section>
    </main>
    <footer id="help"><div className="footer-top"><a className="brand footer-brand" href="#top"><span className="brand-mark">c</span><span>crib<span>seekers</span></span></a><p>Find. Inspect. Secure.</p><a className="join" href="#signup">Start your search <ArrowRight size={16}/></a></div><div className="footer-links"><div><strong>Explore</strong><a>Find homes</a><a>Popular locations</a><a>AI Search</a><a>List a property</a></div><div><strong>Company</strong><a>About us</a><a>Careers</a><a>Blog</a><a>Contact</a></div><div><strong>Support</strong><a>Help center</a><a>Safety center</a><a>Terms of service</a><a>Privacy policy</a></div><div className="newsletter"><strong>Good homes, good news.</strong><p>Thoughtful property insights, delivered occasionally.</p><div><input aria-label="Email address" placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight size={18}/></button></div></div></div><div className="footer-bottom"><span>© 2026 CribSeekers. All rights reserved.</span><span>Made with care in Nigeria <span className="nigeria-dot"></span></span></div></footer>
  </div>
}
createRoot(document.getElementById('root')).render(<App />);
