/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthVerifyPhoneRouteImport } from './routes/auth.verify-phone'
import { Route as BuyerDashboardRouteImport } from './routes/buyer.dashboard'
import { Route as BuyerEscrowRouteImport } from './routes/buyer.escrow'
import { Route as BuyerInspectionsRouteImport } from './routes/buyer.inspections'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer.notifications'
import { Route as BuyerProfileRouteImport } from './routes/buyer.profile'
import { Route as BuyerSavedRouteImport } from './routes/buyer.saved'
import { Route as BuyerSearchRouteImport } from './routes/buyer.search'
import { Route as BuyerSettingsRouteImport } from './routes/buyer.settings'
import { Route as BuyerWalletRouteImport } from './routes/buyer.wallet'
import { Route as LandlordDashboardRouteImport } from './routes/landlord.dashboard'
import { Route as LandlordPaymentsRouteImport } from './routes/landlord.payments'
import { Route as LandlordPropertiesRouteImport } from './routes/landlord.properties'
import { Route as LandlordTenantsRouteImport } from './routes/landlord.tenants'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as TenantDashboardRouteImport } from './routes/tenant.dashboard'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant.maintenance'
import { Route as TenantMessagesRouteImport } from './routes/tenant.messages'
import { Route as TenantNotificationsRouteImport } from './routes/tenant.notifications'
import { Route as TenantPaymentsRouteImport } from './routes/tenant.payments'
import { Route as TenantProfileRouteImport } from './routes/tenant.profile'
import { Route as TenantRentalsRouteImport } from './routes/tenant.rentals'
import { Route as TenantSettingsRouteImport } from './routes/tenant.settings'
import { Route as TenantWalletRouteImport } from './routes/tenant.wallet'
import { Route as AuthSignupRoleRouteImport } from './routes/auth.signup.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyPhoneRoute = AuthVerifyPhoneRouteImport.update({
  id: '/auth/verify-phone',
  path: '/auth/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerEscrowRoute = BuyerEscrowRouteImport.update({
  id: '/buyer/escrow',
  path: '/buyer/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerInspectionsRoute = BuyerInspectionsRouteImport.update({
  id: '/buyer/inspections',
  path: '/buyer/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/buyer/messages',
  path: '/buyer/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/buyer/notifications',
  path: '/buyer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProfileRoute = BuyerProfileRouteImport.update({
  id: '/buyer/profile',
  path: '/buyer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSavedRoute = BuyerSavedRouteImport.update({
  id: '/buyer/saved',
  path: '/buyer/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSearchRoute = BuyerSearchRouteImport.update({
  id: '/buyer/search',
  path: '/buyer/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSettingsRoute = BuyerSettingsRouteImport.update({
  id: '/buyer/settings',
  path: '/buyer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerWalletRoute = BuyerWalletRouteImport.update({
  id: '/buyer/wallet',
  path: '/buyer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordDashboardRoute = LandlordDashboardRouteImport.update({
  id: '/landlord/dashboard',
  path: '/landlord/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPaymentsRoute = LandlordPaymentsRouteImport.update({
  id: '/landlord/payments',
  path: '/landlord/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPropertiesRoute = LandlordPropertiesRouteImport.update({
  id: '/landlord/properties',
  path: '/landlord/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordTenantsRoute = LandlordTenantsRouteImport.update({
  id: '/landlord/tenants',
  path: '/landlord/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/tenant/dashboard',
  path: '/tenant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/tenant/maintenance',
  path: '/tenant/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMessagesRoute = TenantMessagesRouteImport.update({
  id: '/tenant/messages',
  path: '/tenant/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantNotificationsRoute = TenantNotificationsRouteImport.update({
  id: '/tenant/notifications',
  path: '/tenant/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPaymentsRoute = TenantPaymentsRouteImport.update({
  id: '/tenant/payments',
  path: '/tenant/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantProfileRoute = TenantProfileRouteImport.update({
  id: '/tenant/profile',
  path: '/tenant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRentalsRoute = TenantRentalsRouteImport.update({
  id: '/tenant/rentals',
  path: '/tenant/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/tenant/settings',
  path: '/tenant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantWalletRoute = TenantWalletRouteImport.update({
  id: '/tenant/wallet',
  path: '/tenant/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoleRoute = AuthSignupRoleRouteImport.update({
  id: '/auth/signup/$role',
  path: '/auth/signup/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/escrow': typeof BuyerEscrowRoute
  '/buyer/inspections': typeof BuyerInspectionsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/saved': typeof BuyerSavedRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/landlord/dashboard': typeof LandlordDashboardRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/property/$id': typeof PropertyIdRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/messages': typeof TenantMessagesRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/wallet': typeof TenantWalletRoute
  '/auth/signup/$role': typeof AuthSignupRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/escrow': typeof BuyerEscrowRoute
  '/buyer/inspections': typeof BuyerInspectionsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/saved': typeof BuyerSavedRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/landlord/dashboard': typeof LandlordDashboardRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/property/$id': typeof PropertyIdRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/messages': typeof TenantMessagesRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/wallet': typeof TenantWalletRoute
  '/auth/signup/$role': typeof AuthSignupRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/escrow': typeof BuyerEscrowRoute
  '/buyer/inspections': typeof BuyerInspectionsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/saved': typeof BuyerSavedRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/landlord/dashboard': typeof LandlordDashboardRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/property/$id': typeof PropertyIdRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/messages': typeof TenantMessagesRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/wallet': typeof TenantWalletRoute
  '/auth/signup/$role': typeof AuthSignupRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/legal'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/buyer/dashboard'
    | '/buyer/escrow'
    | '/buyer/inspections'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/profile'
    | '/buyer/saved'
    | '/buyer/search'
    | '/buyer/settings'
    | '/buyer/wallet'
    | '/landlord/dashboard'
    | '/landlord/payments'
    | '/landlord/properties'
    | '/landlord/tenants'
    | '/property/$id'
    | '/tenant/dashboard'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/rentals'
    | '/tenant/settings'
    | '/tenant/wallet'
    | '/auth/signup/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/legal'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/buyer/dashboard'
    | '/buyer/escrow'
    | '/buyer/inspections'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/profile'
    | '/buyer/saved'
    | '/buyer/search'
    | '/buyer/settings'
    | '/buyer/wallet'
    | '/landlord/dashboard'
    | '/landlord/payments'
    | '/landlord/properties'
    | '/landlord/tenants'
    | '/property/$id'
    | '/tenant/dashboard'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/rentals'
    | '/tenant/settings'
    | '/tenant/wallet'
    | '/auth/signup/$role'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/legal'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/buyer/dashboard'
    | '/buyer/escrow'
    | '/buyer/inspections'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/profile'
    | '/buyer/saved'
    | '/buyer/search'
    | '/buyer/settings'
    | '/buyer/wallet'
    | '/landlord/dashboard'
    | '/landlord/payments'
    | '/landlord/properties'
    | '/landlord/tenants'
    | '/property/$id'
    | '/tenant/dashboard'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/rentals'
    | '/tenant/settings'
    | '/tenant/wallet'
    | '/auth/signup/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  LegalRoute: typeof LegalRoute
  SearchRoute: typeof SearchRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyPhoneRoute: typeof AuthVerifyPhoneRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  BuyerEscrowRoute: typeof BuyerEscrowRoute
  BuyerInspectionsRoute: typeof BuyerInspectionsRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerProfileRoute: typeof BuyerProfileRoute
  BuyerSavedRoute: typeof BuyerSavedRoute
  BuyerSearchRoute: typeof BuyerSearchRoute
  BuyerSettingsRoute: typeof BuyerSettingsRoute
  BuyerWalletRoute: typeof BuyerWalletRoute
  LandlordDashboardRoute: typeof LandlordDashboardRoute
  LandlordPaymentsRoute: typeof LandlordPaymentsRoute
  LandlordPropertiesRoute: typeof LandlordPropertiesRoute
  LandlordTenantsRoute: typeof LandlordTenantsRoute
  PropertyIdRoute: typeof PropertyIdRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantMessagesRoute: typeof TenantMessagesRoute
  TenantNotificationsRoute: typeof TenantNotificationsRoute
  TenantPaymentsRoute: typeof TenantPaymentsRoute
  TenantProfileRoute: typeof TenantProfileRoute
  TenantRentalsRoute: typeof TenantRentalsRoute
  TenantSettingsRoute: typeof TenantSettingsRoute
  TenantWalletRoute: typeof TenantWalletRoute
  AuthSignupRoleRoute: typeof AuthSignupRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-phone': {
      id: '/auth/verify-phone'
      path: '/auth/verify-phone'
      fullPath: '/auth/verify-phone'
      preLoaderRoute: typeof AuthVerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/escrow': {
      id: '/buyer/escrow'
      path: '/buyer/escrow'
      fullPath: '/buyer/escrow'
      preLoaderRoute: typeof BuyerEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/inspections': {
      id: '/buyer/inspections'
      path: '/buyer/inspections'
      fullPath: '/buyer/inspections'
      preLoaderRoute: typeof BuyerInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/buyer/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/buyer/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/profile': {
      id: '/buyer/profile'
      path: '/buyer/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof BuyerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/saved': {
      id: '/buyer/saved'
      path: '/buyer/saved'
      fullPath: '/buyer/saved'
      preLoaderRoute: typeof BuyerSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/search': {
      id: '/buyer/search'
      path: '/buyer/search'
      fullPath: '/buyer/search'
      preLoaderRoute: typeof BuyerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/settings': {
      id: '/buyer/settings'
      path: '/buyer/settings'
      fullPath: '/buyer/settings'
      preLoaderRoute: typeof BuyerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/wallet': {
      id: '/buyer/wallet'
      path: '/buyer/wallet'
      fullPath: '/buyer/wallet'
      preLoaderRoute: typeof BuyerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/dashboard': {
      id: '/landlord/dashboard'
      path: '/landlord/dashboard'
      fullPath: '/landlord/dashboard'
      preLoaderRoute: typeof LandlordDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/payments': {
      id: '/landlord/payments'
      path: '/landlord/payments'
      fullPath: '/landlord/payments'
      preLoaderRoute: typeof LandlordPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/properties': {
      id: '/landlord/properties'
      path: '/landlord/properties'
      fullPath: '/landlord/properties'
      preLoaderRoute: typeof LandlordPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/tenants': {
      id: '/landlord/tenants'
      path: '/landlord/tenants'
      fullPath: '/landlord/tenants'
      preLoaderRoute: typeof LandlordTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/tenant/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/messages': {
      id: '/tenant/messages'
      path: '/tenant/messages'
      fullPath: '/tenant/messages'
      preLoaderRoute: typeof TenantMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/notifications': {
      id: '/tenant/notifications'
      path: '/tenant/notifications'
      fullPath: '/tenant/notifications'
      preLoaderRoute: typeof TenantNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/profile': {
      id: '/tenant/profile'
      path: '/tenant/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof TenantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/rentals': {
      id: '/tenant/rentals'
      path: '/tenant/rentals'
      fullPath: '/tenant/rentals'
      preLoaderRoute: typeof TenantRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settings': {
      id: '/tenant/settings'
      path: '/tenant/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/wallet': {
      id: '/tenant/wallet'
      path: '/tenant/wallet'
      fullPath: '/tenant/wallet'
      preLoaderRoute: typeof TenantWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/$role': {
      id: '/auth/signup/$role'
      path: '/auth/signup/$role'
      fullPath: '/auth/signup/$role'
      preLoaderRoute: typeof AuthSignupRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  LegalRoute: LegalRoute,
  SearchRoute: SearchRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyPhoneRoute: AuthVerifyPhoneRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  BuyerEscrowRoute: BuyerEscrowRoute,
  BuyerInspectionsRoute: BuyerInspectionsRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerProfileRoute: BuyerProfileRoute,
  BuyerSavedRoute: BuyerSavedRoute,
  BuyerSearchRoute: BuyerSearchRoute,
  BuyerSettingsRoute: BuyerSettingsRoute,
  BuyerWalletRoute: BuyerWalletRoute,
  LandlordDashboardRoute: LandlordDashboardRoute,
  LandlordPaymentsRoute: LandlordPaymentsRoute,
  LandlordPropertiesRoute: LandlordPropertiesRoute,
  LandlordTenantsRoute: LandlordTenantsRoute,
  PropertyIdRoute: PropertyIdRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantMessagesRoute: TenantMessagesRoute,
  TenantNotificationsRoute: TenantNotificationsRoute,
  TenantPaymentsRoute: TenantPaymentsRoute,
  TenantProfileRoute: TenantProfileRoute,
  TenantRentalsRoute: TenantRentalsRoute,
  TenantSettingsRoute: TenantSettingsRoute,
  TenantWalletRoute: TenantWalletRoute,
  AuthSignupRoleRoute: AuthSignupRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
