/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AgentAppointmentsRouteImport } from './routes/agent.appointments'
import { Route as AgentClientsRouteImport } from './routes/agent.clients'
import { Route as AgentCommissionsRouteImport } from './routes/agent.commissions'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AgentDealsRouteImport } from './routes/agent.deals'
import { Route as AgentLeadsRouteImport } from './routes/agent.leads'
import { Route as AgentListingsRouteImport } from './routes/agent.listings'
import { Route as AgentMessagesRouteImport } from './routes/agent.messages'
import { Route as AgentNotificationsRouteImport } from './routes/agent.notifications'
import { Route as AgentProfileRouteImport } from './routes/agent.profile'
import { Route as AgentSettingsRouteImport } from './routes/agent.settings'
import { Route as AgentWalletRouteImport } from './routes/agent.wallet'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthVerifyPhoneRouteImport } from './routes/auth.verify-phone'
import { Route as BuyerDashboardRouteImport } from './routes/buyer.dashboard'
import { Route as BuyerEscrowRouteImport } from './routes/buyer.escrow'
import { Route as BuyerInspectionsRouteImport } from './routes/buyer.inspections'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer.notifications'
import { Route as BuyerProfileRouteImport } from './routes/buyer.profile'
import { Route as BuyerSavedRouteImport } from './routes/buyer.saved'
import { Route as BuyerSearchRouteImport } from './routes/buyer.search'
import { Route as BuyerSettingsRouteImport } from './routes/buyer.settings'
import { Route as BuyerWalletRouteImport } from './routes/buyer.wallet'
import { Route as DeveloperConstructionRouteImport } from './routes/developer.construction'
import { Route as DeveloperDashboardRouteImport } from './routes/developer.dashboard'
import { Route as DeveloperMessagesRouteImport } from './routes/developer.messages'
import { Route as DeveloperNotificationsRouteImport } from './routes/developer.notifications'
import { Route as DeveloperProfileRouteImport } from './routes/developer.profile'
import { Route as DeveloperProjectsRouteImport } from './routes/developer.projects'
import { Route as DeveloperReportsRouteImport } from './routes/developer.reports'
import { Route as DeveloperReservationsRouteImport } from './routes/developer.reservations'
import { Route as DeveloperSalesRouteImport } from './routes/developer.sales'
import { Route as DeveloperSettingsRouteImport } from './routes/developer.settings'
import { Route as DeveloperUnitsRouteImport } from './routes/developer.units'
import { Route as DeveloperWalletRouteImport } from './routes/developer.wallet'
import { Route as LandlordDashboardRouteImport } from './routes/landlord.dashboard'
import { Route as LandlordMessagesRouteImport } from './routes/landlord.messages'
import { Route as LandlordNotificationsRouteImport } from './routes/landlord.notifications'
import { Route as LandlordPaymentsRouteImport } from './routes/landlord.payments'
import { Route as LandlordProfileRouteImport } from './routes/landlord.profile'
import { Route as LandlordPropertiesRouteImport } from './routes/landlord.properties'
import { Route as LandlordSettingsRouteImport } from './routes/landlord.settings'
import { Route as LandlordTenantsRouteImport } from './routes/landlord.tenants'
import { Route as LandlordWalletRouteImport } from './routes/landlord.wallet'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as TenantDashboardRouteImport } from './routes/tenant.dashboard'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant.maintenance'
import { Route as TenantMessagesRouteImport } from './routes/tenant.messages'
import { Route as TenantNotificationsRouteImport } from './routes/tenant.notifications'
import { Route as TenantPaymentsRouteImport } from './routes/tenant.payments'
import { Route as TenantProfileRouteImport } from './routes/tenant.profile'
import { Route as TenantRentalsRouteImport } from './routes/tenant.rentals'
import { Route as TenantSettingsRouteImport } from './routes/tenant.settings'
import { Route as TenantWalletRouteImport } from './routes/tenant.wallet'
import { Route as AuthSignupRoleRouteImport } from './routes/auth.signup.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAppointmentsRoute = AgentAppointmentsRouteImport.update({
  id: '/agent/appointments',
  path: '/agent/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentClientsRoute = AgentClientsRouteImport.update({
  id: '/agent/clients',
  path: '/agent/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCommissionsRoute = AgentCommissionsRouteImport.update({
  id: '/agent/commissions',
  path: '/agent/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDealsRoute = AgentDealsRouteImport.update({
  id: '/agent/deals',
  path: '/agent/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLeadsRoute = AgentLeadsRouteImport.update({
  id: '/agent/leads',
  path: '/agent/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentListingsRoute = AgentListingsRouteImport.update({
  id: '/agent/listings',
  path: '/agent/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMessagesRoute = AgentMessagesRouteImport.update({
  id: '/agent/messages',
  path: '/agent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentNotificationsRoute = AgentNotificationsRouteImport.update({
  id: '/agent/notifications',
  path: '/agent/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSettingsRoute = AgentSettingsRouteImport.update({
  id: '/agent/settings',
  path: '/agent/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWalletRoute = AgentWalletRouteImport.update({
  id: '/agent/wallet',
  path: '/agent/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyPhoneRoute = AuthVerifyPhoneRouteImport.update({
  id: '/auth/verify-phone',
  path: '/auth/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerEscrowRoute = BuyerEscrowRouteImport.update({
  id: '/buyer/escrow',
  path: '/buyer/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerInspectionsRoute = BuyerInspectionsRouteImport.update({
  id: '/buyer/inspections',
  path: '/buyer/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/buyer/messages',
  path: '/buyer/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/buyer/notifications',
  path: '/buyer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProfileRoute = BuyerProfileRouteImport.update({
  id: '/buyer/profile',
  path: '/buyer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSavedRoute = BuyerSavedRouteImport.update({
  id: '/buyer/saved',
  path: '/buyer/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSearchRoute = BuyerSearchRouteImport.update({
  id: '/buyer/search',
  path: '/buyer/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSettingsRoute = BuyerSettingsRouteImport.update({
  id: '/buyer/settings',
  path: '/buyer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerWalletRoute = BuyerWalletRouteImport.update({
  id: '/buyer/wallet',
  path: '/buyer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperConstructionRoute = DeveloperConstructionRouteImport.update({
  id: '/developer/construction',
  path: '/developer/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDashboardRoute = DeveloperDashboardRouteImport.update({
  id: '/developer/dashboard',
  path: '/developer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperMessagesRoute = DeveloperMessagesRouteImport.update({
  id: '/developer/messages',
  path: '/developer/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperNotificationsRoute = DeveloperNotificationsRouteImport.update({
  id: '/developer/notifications',
  path: '/developer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProfileRoute = DeveloperProfileRouteImport.update({
  id: '/developer/profile',
  path: '/developer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectsRoute = DeveloperProjectsRouteImport.update({
  id: '/developer/projects',
  path: '/developer/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperReportsRoute = DeveloperReportsRouteImport.update({
  id: '/developer/reports',
  path: '/developer/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperReservationsRoute = DeveloperReservationsRouteImport.update({
  id: '/developer/reservations',
  path: '/developer/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSalesRoute = DeveloperSalesRouteImport.update({
  id: '/developer/sales',
  path: '/developer/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSettingsRoute = DeveloperSettingsRouteImport.update({
  id: '/developer/settings',
  path: '/developer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperUnitsRoute = DeveloperUnitsRouteImport.update({
  id: '/developer/units',
  path: '/developer/units',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperWalletRoute = DeveloperWalletRouteImport.update({
  id: '/developer/wallet',
  path: '/developer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordDashboardRoute = LandlordDashboardRouteImport.update({
  id: '/landlord/dashboard',
  path: '/landlord/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordMessagesRoute = LandlordMessagesRouteImport.update({
  id: '/landlord/messages',
  path: '/landlord/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordNotificationsRoute = LandlordNotificationsRouteImport.update({
  id: '/landlord/notifications',
  path: '/landlord/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPaymentsRoute = LandlordPaymentsRouteImport.update({
  id: '/landlord/payments',
  path: '/landlord/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordProfileRoute = LandlordProfileRouteImport.update({
  id: '/landlord/profile',
  path: '/landlord/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPropertiesRoute = LandlordPropertiesRouteImport.update({
  id: '/landlord/properties',
  path: '/landlord/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordSettingsRoute = LandlordSettingsRouteImport.update({
  id: '/landlord/settings',
  path: '/landlord/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordTenantsRoute = LandlordTenantsRouteImport.update({
  id: '/landlord/tenants',
  path: '/landlord/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordWalletRoute = LandlordWalletRouteImport.update({
  id: '/landlord/wallet',
  path: '/landlord/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/tenant/dashboard',
  path: '/tenant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/tenant/maintenance',
  path: '/tenant/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMessagesRoute = TenantMessagesRouteImport.update({
  id: '/tenant/messages',
  path: '/tenant/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantNotificationsRoute = TenantNotificationsRouteImport.update({
  id: '/tenant/notifications',
  path: '/tenant/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPaymentsRoute = TenantPaymentsRouteImport.update({
  id: '/tenant/payments',
  path: '/tenant/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantProfileRoute = TenantProfileRouteImport.update({
  id: '/tenant/profile',
  path: '/tenant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRentalsRoute = TenantRentalsRouteImport.update({
  id: '/tenant/rentals',
  path: '/tenant/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/tenant/settings',
  path: '/tenant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantWalletRoute = TenantWalletRouteImport.update({
  id: '/tenant/wallet',
  path: '/tenant/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoleRoute = AuthSignupRoleRouteImport.update({
  id: '/auth/signup/$role',
  path: '/auth/signup/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/agent/appointments': typeof AgentAppointmentsRoute
  '/agent/clients': typeof AgentClientsRoute
  '/agent/commissions': typeof AgentCommissionsRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/deals': typeof AgentDealsRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/listings': typeof AgentListingsRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/notifications': typeof AgentNotificationsRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/agent/wallet': typeof AgentWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/escrow': typeof BuyerEscrowRoute
  '/buyer/inspections': typeof BuyerInspectionsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/saved': typeof BuyerSavedRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/developer/construction': typeof DeveloperConstructionRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/notifications': typeof DeveloperNotificationsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/developer/reports': typeof DeveloperReportsRoute
  '/developer/reservations': typeof DeveloperReservationsRoute
  '/developer/sales': typeof DeveloperSalesRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/units': typeof DeveloperUnitsRoute
  '/developer/wallet': typeof DeveloperWalletRoute
  '/landlord/dashboard': typeof LandlordDashboardRoute
  '/landlord/messages': typeof LandlordMessagesRoute
  '/landlord/notifications': typeof LandlordNotificationsRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/profile': typeof LandlordProfileRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/settings': typeof LandlordSettingsRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/landlord/wallet': typeof LandlordWalletRoute
  '/property/$id': typeof PropertyIdRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/messages': typeof TenantMessagesRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/wallet': typeof TenantWalletRoute
  '/auth/signup/$role': typeof AuthSignupRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/agent/appointments': typeof AgentAppointmentsRoute
  '/agent/clients': typeof AgentClientsRoute
  '/agent/commissions': typeof AgentCommissionsRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/deals': typeof AgentDealsRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/listings': typeof AgentListingsRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/notifications': typeof AgentNotificationsRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/agent/wallet': typeof AgentWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/escrow': typeof BuyerEscrowRoute
  '/buyer/inspections': typeof BuyerInspectionsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/saved': typeof BuyerSavedRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/developer/construction': typeof DeveloperConstructionRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/notifications': typeof DeveloperNotificationsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/developer/reports': typeof DeveloperReportsRoute
  '/developer/reservations': typeof DeveloperReservationsRoute
  '/developer/sales': typeof DeveloperSalesRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/units': typeof DeveloperUnitsRoute
  '/developer/wallet': typeof DeveloperWalletRoute
  '/landlord/dashboard': typeof LandlordDashboardRoute
  '/landlord/messages': typeof LandlordMessagesRoute
  '/landlord/notifications': typeof LandlordNotificationsRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/profile': typeof LandlordProfileRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/settings': typeof LandlordSettingsRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/landlord/wallet': typeof LandlordWalletRoute
  '/property/$id': typeof PropertyIdRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/messages': typeof TenantMessagesRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/wallet': typeof TenantWalletRoute
  '/auth/signup/$role': typeof AuthSignupRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/agent/appointments': typeof AgentAppointmentsRoute
  '/agent/clients': typeof AgentClientsRoute
  '/agent/commissions': typeof AgentCommissionsRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/deals': typeof AgentDealsRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/listings': typeof AgentListingsRoute
  '/agent/messages': typeof AgentMessagesRoute
  '/agent/notifications': typeof AgentNotificationsRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/agent/wallet': typeof AgentWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/escrow': typeof BuyerEscrowRoute
  '/buyer/inspections': typeof BuyerInspectionsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/profile': typeof BuyerProfileRoute
  '/buyer/saved': typeof BuyerSavedRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/settings': typeof BuyerSettingsRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/developer/construction': typeof DeveloperConstructionRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/notifications': typeof DeveloperNotificationsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/developer/reports': typeof DeveloperReportsRoute
  '/developer/reservations': typeof DeveloperReservationsRoute
  '/developer/sales': typeof DeveloperSalesRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/units': typeof DeveloperUnitsRoute
  '/developer/wallet': typeof DeveloperWalletRoute
  '/landlord/dashboard': typeof LandlordDashboardRoute
  '/landlord/messages': typeof LandlordMessagesRoute
  '/landlord/notifications': typeof LandlordNotificationsRoute
  '/landlord/payments': typeof LandlordPaymentsRoute
  '/landlord/profile': typeof LandlordProfileRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/settings': typeof LandlordSettingsRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/landlord/wallet': typeof LandlordWalletRoute
  '/property/$id': typeof PropertyIdRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/messages': typeof TenantMessagesRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/tenant/settings': typeof TenantSettingsRoute
  '/tenant/wallet': typeof TenantWalletRoute
  '/auth/signup/$role': typeof AuthSignupRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/legal'
    | '/search'
    | '/agent/appointments'
    | '/agent/clients'
    | '/agent/commissions'
    | '/agent/dashboard'
    | '/agent/deals'
    | '/agent/leads'
    | '/agent/listings'
    | '/agent/messages'
    | '/agent/notifications'
    | '/agent/profile'
    | '/agent/settings'
    | '/agent/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/buyer/dashboard'
    | '/buyer/escrow'
    | '/buyer/inspections'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/profile'
    | '/buyer/saved'
    | '/buyer/search'
    | '/buyer/settings'
    | '/buyer/wallet'
    | '/developer/construction'
    | '/developer/dashboard'
    | '/developer/messages'
    | '/developer/notifications'
    | '/developer/profile'
    | '/developer/projects'
    | '/developer/reports'
    | '/developer/reservations'
    | '/developer/sales'
    | '/developer/settings'
    | '/developer/units'
    | '/developer/wallet'
    | '/landlord/dashboard'
    | '/landlord/messages'
    | '/landlord/notifications'
    | '/landlord/payments'
    | '/landlord/profile'
    | '/landlord/properties'
    | '/landlord/settings'
    | '/landlord/tenants'
    | '/landlord/wallet'
    | '/property/$id'
    | '/tenant/dashboard'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/rentals'
    | '/tenant/settings'
    | '/tenant/wallet'
    | '/auth/signup/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/legal'
    | '/search'
    | '/agent/appointments'
    | '/agent/clients'
    | '/agent/commissions'
    | '/agent/dashboard'
    | '/agent/deals'
    | '/agent/leads'
    | '/agent/listings'
    | '/agent/messages'
    | '/agent/notifications'
    | '/agent/profile'
    | '/agent/settings'
    | '/agent/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/buyer/dashboard'
    | '/buyer/escrow'
    | '/buyer/inspections'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/profile'
    | '/buyer/saved'
    | '/buyer/search'
    | '/buyer/settings'
    | '/buyer/wallet'
    | '/developer/construction'
    | '/developer/dashboard'
    | '/developer/messages'
    | '/developer/notifications'
    | '/developer/profile'
    | '/developer/projects'
    | '/developer/reports'
    | '/developer/reservations'
    | '/developer/sales'
    | '/developer/settings'
    | '/developer/units'
    | '/developer/wallet'
    | '/landlord/dashboard'
    | '/landlord/messages'
    | '/landlord/notifications'
    | '/landlord/payments'
    | '/landlord/profile'
    | '/landlord/properties'
    | '/landlord/settings'
    | '/landlord/tenants'
    | '/landlord/wallet'
    | '/property/$id'
    | '/tenant/dashboard'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/rentals'
    | '/tenant/settings'
    | '/tenant/wallet'
    | '/auth/signup/$role'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/legal'
    | '/search'
    | '/agent/appointments'
    | '/agent/clients'
    | '/agent/commissions'
    | '/agent/dashboard'
    | '/agent/deals'
    | '/agent/leads'
    | '/agent/listings'
    | '/agent/messages'
    | '/agent/notifications'
    | '/agent/profile'
    | '/agent/settings'
    | '/agent/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/role'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/buyer/dashboard'
    | '/buyer/escrow'
    | '/buyer/inspections'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/profile'
    | '/buyer/saved'
    | '/buyer/search'
    | '/buyer/settings'
    | '/buyer/wallet'
    | '/developer/construction'
    | '/developer/dashboard'
    | '/developer/messages'
    | '/developer/notifications'
    | '/developer/profile'
    | '/developer/projects'
    | '/developer/reports'
    | '/developer/reservations'
    | '/developer/sales'
    | '/developer/settings'
    | '/developer/units'
    | '/developer/wallet'
    | '/landlord/dashboard'
    | '/landlord/messages'
    | '/landlord/notifications'
    | '/landlord/payments'
    | '/landlord/profile'
    | '/landlord/properties'
    | '/landlord/settings'
    | '/landlord/tenants'
    | '/landlord/wallet'
    | '/property/$id'
    | '/tenant/dashboard'
    | '/tenant/maintenance'
    | '/tenant/messages'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/rentals'
    | '/tenant/settings'
    | '/tenant/wallet'
    | '/auth/signup/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  LegalRoute: typeof LegalRoute
  SearchRoute: typeof SearchRoute
  AgentAppointmentsRoute: typeof AgentAppointmentsRoute
  AgentClientsRoute: typeof AgentClientsRoute
  AgentCommissionsRoute: typeof AgentCommissionsRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentDealsRoute: typeof AgentDealsRoute
  AgentLeadsRoute: typeof AgentLeadsRoute
  AgentListingsRoute: typeof AgentListingsRoute
  AgentMessagesRoute: typeof AgentMessagesRoute
  AgentNotificationsRoute: typeof AgentNotificationsRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentSettingsRoute: typeof AgentSettingsRoute
  AgentWalletRoute: typeof AgentWalletRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyPhoneRoute: typeof AuthVerifyPhoneRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  BuyerEscrowRoute: typeof BuyerEscrowRoute
  BuyerInspectionsRoute: typeof BuyerInspectionsRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerProfileRoute: typeof BuyerProfileRoute
  BuyerSavedRoute: typeof BuyerSavedRoute
  BuyerSearchRoute: typeof BuyerSearchRoute
  BuyerSettingsRoute: typeof BuyerSettingsRoute
  BuyerWalletRoute: typeof BuyerWalletRoute
  DeveloperConstructionRoute: typeof DeveloperConstructionRoute
  DeveloperDashboardRoute: typeof DeveloperDashboardRoute
  DeveloperMessagesRoute: typeof DeveloperMessagesRoute
  DeveloperNotificationsRoute: typeof DeveloperNotificationsRoute
  DeveloperProfileRoute: typeof DeveloperProfileRoute
  DeveloperProjectsRoute: typeof DeveloperProjectsRoute
  DeveloperReportsRoute: typeof DeveloperReportsRoute
  DeveloperReservationsRoute: typeof DeveloperReservationsRoute
  DeveloperSalesRoute: typeof DeveloperSalesRoute
  DeveloperSettingsRoute: typeof DeveloperSettingsRoute
  DeveloperUnitsRoute: typeof DeveloperUnitsRoute
  DeveloperWalletRoute: typeof DeveloperWalletRoute
  LandlordDashboardRoute: typeof LandlordDashboardRoute
  LandlordMessagesRoute: typeof LandlordMessagesRoute
  LandlordNotificationsRoute: typeof LandlordNotificationsRoute
  LandlordPaymentsRoute: typeof LandlordPaymentsRoute
  LandlordProfileRoute: typeof LandlordProfileRoute
  LandlordPropertiesRoute: typeof LandlordPropertiesRoute
  LandlordSettingsRoute: typeof LandlordSettingsRoute
  LandlordTenantsRoute: typeof LandlordTenantsRoute
  LandlordWalletRoute: typeof LandlordWalletRoute
  PropertyIdRoute: typeof PropertyIdRoute
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantMessagesRoute: typeof TenantMessagesRoute
  TenantNotificationsRoute: typeof TenantNotificationsRoute
  TenantPaymentsRoute: typeof TenantPaymentsRoute
  TenantProfileRoute: typeof TenantProfileRoute
  TenantRentalsRoute: typeof TenantRentalsRoute
  TenantSettingsRoute: typeof TenantSettingsRoute
  TenantWalletRoute: typeof TenantWalletRoute
  AuthSignupRoleRoute: typeof AuthSignupRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/appointments': {
      id: '/agent/appointments'
      path: '/agent/appointments'
      fullPath: '/agent/appointments'
      preLoaderRoute: typeof AgentAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/clients': {
      id: '/agent/clients'
      path: '/agent/clients'
      fullPath: '/agent/clients'
      preLoaderRoute: typeof AgentClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/commissions': {
      id: '/agent/commissions'
      path: '/agent/commissions'
      fullPath: '/agent/commissions'
      preLoaderRoute: typeof AgentCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/deals': {
      id: '/agent/deals'
      path: '/agent/deals'
      fullPath: '/agent/deals'
      preLoaderRoute: typeof AgentDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/leads': {
      id: '/agent/leads'
      path: '/agent/leads'
      fullPath: '/agent/leads'
      preLoaderRoute: typeof AgentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/listings': {
      id: '/agent/listings'
      path: '/agent/listings'
      fullPath: '/agent/listings'
      preLoaderRoute: typeof AgentListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/messages': {
      id: '/agent/messages'
      path: '/agent/messages'
      fullPath: '/agent/messages'
      preLoaderRoute: typeof AgentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/notifications': {
      id: '/agent/notifications'
      path: '/agent/notifications'
      fullPath: '/agent/notifications'
      preLoaderRoute: typeof AgentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/settings': {
      id: '/agent/settings'
      path: '/agent/settings'
      fullPath: '/agent/settings'
      preLoaderRoute: typeof AgentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/wallet': {
      id: '/agent/wallet'
      path: '/agent/wallet'
      fullPath: '/agent/wallet'
      preLoaderRoute: typeof AgentWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-phone': {
      id: '/auth/verify-phone'
      path: '/auth/verify-phone'
      fullPath: '/auth/verify-phone'
      preLoaderRoute: typeof AuthVerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/escrow': {
      id: '/buyer/escrow'
      path: '/buyer/escrow'
      fullPath: '/buyer/escrow'
      preLoaderRoute: typeof BuyerEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/inspections': {
      id: '/buyer/inspections'
      path: '/buyer/inspections'
      fullPath: '/buyer/inspections'
      preLoaderRoute: typeof BuyerInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/buyer/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/buyer/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/profile': {
      id: '/buyer/profile'
      path: '/buyer/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof BuyerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/saved': {
      id: '/buyer/saved'
      path: '/buyer/saved'
      fullPath: '/buyer/saved'
      preLoaderRoute: typeof BuyerSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/search': {
      id: '/buyer/search'
      path: '/buyer/search'
      fullPath: '/buyer/search'
      preLoaderRoute: typeof BuyerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/settings': {
      id: '/buyer/settings'
      path: '/buyer/settings'
      fullPath: '/buyer/settings'
      preLoaderRoute: typeof BuyerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/wallet': {
      id: '/buyer/wallet'
      path: '/buyer/wallet'
      fullPath: '/buyer/wallet'
      preLoaderRoute: typeof BuyerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/construction': {
      id: '/developer/construction'
      path: '/developer/construction'
      fullPath: '/developer/construction'
      preLoaderRoute: typeof DeveloperConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/dashboard': {
      id: '/developer/dashboard'
      path: '/developer/dashboard'
      fullPath: '/developer/dashboard'
      preLoaderRoute: typeof DeveloperDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/messages': {
      id: '/developer/messages'
      path: '/developer/messages'
      fullPath: '/developer/messages'
      preLoaderRoute: typeof DeveloperMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/notifications': {
      id: '/developer/notifications'
      path: '/developer/notifications'
      fullPath: '/developer/notifications'
      preLoaderRoute: typeof DeveloperNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/profile': {
      id: '/developer/profile'
      path: '/developer/profile'
      fullPath: '/developer/profile'
      preLoaderRoute: typeof DeveloperProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/projects': {
      id: '/developer/projects'
      path: '/developer/projects'
      fullPath: '/developer/projects'
      preLoaderRoute: typeof DeveloperProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/reports': {
      id: '/developer/reports'
      path: '/developer/reports'
      fullPath: '/developer/reports'
      preLoaderRoute: typeof DeveloperReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/reservations': {
      id: '/developer/reservations'
      path: '/developer/reservations'
      fullPath: '/developer/reservations'
      preLoaderRoute: typeof DeveloperReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/sales': {
      id: '/developer/sales'
      path: '/developer/sales'
      fullPath: '/developer/sales'
      preLoaderRoute: typeof DeveloperSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/settings': {
      id: '/developer/settings'
      path: '/developer/settings'
      fullPath: '/developer/settings'
      preLoaderRoute: typeof DeveloperSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/units': {
      id: '/developer/units'
      path: '/developer/units'
      fullPath: '/developer/units'
      preLoaderRoute: typeof DeveloperUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/wallet': {
      id: '/developer/wallet'
      path: '/developer/wallet'
      fullPath: '/developer/wallet'
      preLoaderRoute: typeof DeveloperWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/dashboard': {
      id: '/landlord/dashboard'
      path: '/landlord/dashboard'
      fullPath: '/landlord/dashboard'
      preLoaderRoute: typeof LandlordDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/messages': {
      id: '/landlord/messages'
      path: '/landlord/messages'
      fullPath: '/landlord/messages'
      preLoaderRoute: typeof LandlordMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/notifications': {
      id: '/landlord/notifications'
      path: '/landlord/notifications'
      fullPath: '/landlord/notifications'
      preLoaderRoute: typeof LandlordNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/payments': {
      id: '/landlord/payments'
      path: '/landlord/payments'
      fullPath: '/landlord/payments'
      preLoaderRoute: typeof LandlordPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/profile': {
      id: '/landlord/profile'
      path: '/landlord/profile'
      fullPath: '/landlord/profile'
      preLoaderRoute: typeof LandlordProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/properties': {
      id: '/landlord/properties'
      path: '/landlord/properties'
      fullPath: '/landlord/properties'
      preLoaderRoute: typeof LandlordPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/settings': {
      id: '/landlord/settings'
      path: '/landlord/settings'
      fullPath: '/landlord/settings'
      preLoaderRoute: typeof LandlordSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/tenants': {
      id: '/landlord/tenants'
      path: '/landlord/tenants'
      fullPath: '/landlord/tenants'
      preLoaderRoute: typeof LandlordTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/wallet': {
      id: '/landlord/wallet'
      path: '/landlord/wallet'
      fullPath: '/landlord/wallet'
      preLoaderRoute: typeof LandlordWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/tenant/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/messages': {
      id: '/tenant/messages'
      path: '/tenant/messages'
      fullPath: '/tenant/messages'
      preLoaderRoute: typeof TenantMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/notifications': {
      id: '/tenant/notifications'
      path: '/tenant/notifications'
      fullPath: '/tenant/notifications'
      preLoaderRoute: typeof TenantNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/profile': {
      id: '/tenant/profile'
      path: '/tenant/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof TenantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/rentals': {
      id: '/tenant/rentals'
      path: '/tenant/rentals'
      fullPath: '/tenant/rentals'
      preLoaderRoute: typeof TenantRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/settings': {
      id: '/tenant/settings'
      path: '/tenant/settings'
      fullPath: '/tenant/settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/wallet': {
      id: '/tenant/wallet'
      path: '/tenant/wallet'
      fullPath: '/tenant/wallet'
      preLoaderRoute: typeof TenantWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/$role': {
      id: '/auth/signup/$role'
      path: '/auth/signup/$role'
      fullPath: '/auth/signup/$role'
      preLoaderRoute: typeof AuthSignupRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  LegalRoute: LegalRoute,
  SearchRoute: SearchRoute,
  AgentAppointmentsRoute: AgentAppointmentsRoute,
  AgentClientsRoute: AgentClientsRoute,
  AgentCommissionsRoute: AgentCommissionsRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentDealsRoute: AgentDealsRoute,
  AgentLeadsRoute: AgentLeadsRoute,
  AgentListingsRoute: AgentListingsRoute,
  AgentMessagesRoute: AgentMessagesRoute,
  AgentNotificationsRoute: AgentNotificationsRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentSettingsRoute: AgentSettingsRoute,
  AgentWalletRoute: AgentWalletRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyPhoneRoute: AuthVerifyPhoneRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  BuyerEscrowRoute: BuyerEscrowRoute,
  BuyerInspectionsRoute: BuyerInspectionsRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerProfileRoute: BuyerProfileRoute,
  BuyerSavedRoute: BuyerSavedRoute,
  BuyerSearchRoute: BuyerSearchRoute,
  BuyerSettingsRoute: BuyerSettingsRoute,
  BuyerWalletRoute: BuyerWalletRoute,
  DeveloperConstructionRoute: DeveloperConstructionRoute,
  DeveloperDashboardRoute: DeveloperDashboardRoute,
  DeveloperMessagesRoute: DeveloperMessagesRoute,
  DeveloperNotificationsRoute: DeveloperNotificationsRoute,
  DeveloperProfileRoute: DeveloperProfileRoute,
  DeveloperProjectsRoute: DeveloperProjectsRoute,
  DeveloperReportsRoute: DeveloperReportsRoute,
  DeveloperReservationsRoute: DeveloperReservationsRoute,
  DeveloperSalesRoute: DeveloperSalesRoute,
  DeveloperSettingsRoute: DeveloperSettingsRoute,
  DeveloperUnitsRoute: DeveloperUnitsRoute,
  DeveloperWalletRoute: DeveloperWalletRoute,
  LandlordDashboardRoute: LandlordDashboardRoute,
  LandlordMessagesRoute: LandlordMessagesRoute,
  LandlordNotificationsRoute: LandlordNotificationsRoute,
  LandlordPaymentsRoute: LandlordPaymentsRoute,
  LandlordProfileRoute: LandlordProfileRoute,
  LandlordPropertiesRoute: LandlordPropertiesRoute,
  LandlordSettingsRoute: LandlordSettingsRoute,
  LandlordTenantsRoute: LandlordTenantsRoute,
  LandlordWalletRoute: LandlordWalletRoute,
  PropertyIdRoute: PropertyIdRoute,
  TenantDashboardRoute: TenantDashboardRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantMessagesRoute: TenantMessagesRoute,
  TenantNotificationsRoute: TenantNotificationsRoute,
  TenantPaymentsRoute: TenantPaymentsRoute,
  TenantProfileRoute: TenantProfileRoute,
  TenantRentalsRoute: TenantRentalsRoute,
  TenantSettingsRoute: TenantSettingsRoute,
  TenantWalletRoute: TenantWalletRoute,
  AuthSignupRoleRoute: AuthSignupRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
