export declare enum PropertyStatus {
    DRAFT = "DRAFT",
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    RENTED = "RENTED",
    SOLD = "SOLD",
    INACTIVE = "INACTIVE",
    SUSPENDED = "SUSPENDED"
}
export declare enum InspectionStatus {
    PENDING = "PENDING",
    SCHEDULED = "SCHEDULED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    NO_SHOW = "NO_SHOW"
}
export declare enum PaymentStatus {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    REFUNDED = "REFUNDED",
    CANCELLED = "CANCELLED"
}
export declare enum NotificationType {
    SYSTEM = "SYSTEM",
    EMAIL = "EMAIL",
    SMS = "SMS",
    PUSH = "PUSH",
    IN_APP = "IN_APP"
}
export declare enum UserRole {
    ADMIN = "ADMIN",
    AGENT = "AGENT",
    LANDLORD = "LANDLORD",
    TENANT = "TENANT"
}
export declare enum Permission {
    CREATE_PROPERTY = "CREATE_PROPERTY",
    READ_PROPERTY = "READ_PROPERTY",
    UPDATE_PROPERTY = "UPDATE_PROPERTY",
    DELETE_PROPERTY = "DELETE_PROPERTY",
    MANAGE_PROPERTY_STATUS = "MANAGE_PROPERTY_STATUS",
    CREATE_INSPECTION = "CREATE_INSPECTION",
    READ_INSPECTION = "READ_INSPECTION",
    UPDATE_INSPECTION = "UPDATE_INSPECTION",
    DELETE_INSPECTION = "DELETE_INSPECTION",
    APPROVE_INSPECTION = "APPROVE_INSPECTION",
    MANAGE_USERS = "MANAGE_USERS",
    MANAGE_AGENTS = "MANAGE_AGENTS",
    VERIFY_AGENT = "VERIFY_AGENT",
    PROCESS_PAYMENT = "PROCESS_PAYMENT",
    REFUND_PAYMENT = "REFUND_PAYMENT",
    VIEW_TRANSACTIONS = "VIEW_TRANSACTIONS",
    MANAGE_ROLES = "MANAGE_ROLES",
    MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS",
    VIEW_ANALYTICS = "VIEW_ANALYTICS",
    MANAGE_SETTINGS = "MANAGE_SETTINGS"
}
export declare enum PropertyType {
    APARTMENT = "APARTMENT",
    HOUSE = "HOUSE",
    FLAT = "FLAT",
    STUDIO = "STUDIO",
    DUPLEX = "DUPLEX",
    TERRACE = "TERRACE",
    BUNGALOW = "BUNGALOW",
    COMMERCIAL = "COMMERCIAL",
    LAND = "LAND",
    OFFICE = "OFFICE",
    WAREHOUSE = "WAREHOUSE"
}
export declare enum ListingType {
    RENT = "RENT",
    SALE = "SALE",
    SHORT_LET = "SHORT_LET"
}
export declare enum FurnishingType {
    FURNISHED = "FURNISHED",
    SEMI_FURNISHED = "SEMI_FURNISHED",
    UNFURNISHED = "UNFURNISHED"
}
//# sourceMappingURL=enums.d.ts.map